/*
 * Trismedia -- An open source telephony toolkit.
 *
 * Copyright (C) 1999 - 2005, Digium, Inc.
 *
 * Martin Pycko <martinp@digium.com>
 *
 * See http://www.trismedia.org for more information about
 * the Trismedia project. Please do not directly contact
 * any of the maintainers of this project for assistance;
 * the project provides a web site, mailing lists and IRC
 * channels for your use.
 *
 * This program is free software, distributed under the terms of
 * the GNU General Public License Version 2. See the LICENSE file
 * at the top of the source tree.
 */

/*! \file
 * \brief Internal Trismedia hangup causes
 */

#ifndef _TRISMEDIA_CAUSES_H
#define _TRISMEDIA_CAUSES_H

/*! \page AstCauses Hangup Causes for Trismedia

The Trismedia hangup causes are delivered to the dialplan in the
${HANGUPCAUSE} channel variable after a call (after execution
of "dial"). 

In SIP, we have a conversion table to convert between SIP
return codes and Q.931 both ways. This is to improve SIP/ISDN
compatibility.

These are the current codes, based on the Q.931
specification:

	- TRIS_CAUSE_UNALLOCATED				1
	- TRIS_CAUSE_NO_ROUTE_TRANSIT_NET			2
	- TRIS_CAUSE_NO_ROUTE_DESTINATION			3
	- TRIS_CAUSE_CHANNEL_UNACCEPTABLE			6
	- TRIS_CAUSE_CALL_AWARDED_DELIVERED		7
	- TRIS_CAUSE_NORMAL_CLEARING			16
	- TRIS_CAUSE_USER_BUSY				17
	- TRIS_CAUSE_NO_USER_RESPONSE			18
	- TRIS_CAUSE_NO_ANSWER				19
	- TRIS_CAUSE_CALL_REJECTED				21
	- TRIS_CAUSE_NUMBER_CHANGED			22
	- TRIS_CAUSE_DESTINATION_OUT_OF_ORDER		27
	- TRIS_CAUSE_INVALID_NUMBER_FORMAT			28
	- TRIS_CAUSE_FACILITY_REJECTED			29
	- TRIS_CAUSE_RESPONSE_TO_STATUS_ENQUIRY		30
	- TRIS_CAUSE_NORMAL_UNSPECIFIED			31
	- TRIS_CAUSE_NORMAL_CIRCUIT_CONGESTION		34
	- TRIS_CAUSE_NETWORK_OUT_OF_ORDER			38
	- TRIS_CAUSE_NORMAL_TEMPORARY_FAILURE		41
	- TRIS_CAUSE_SWITCH_CONGESTION			42
	- TRIS_CAUSE_ACCESS_INFO_DISCARDED			43
	- TRIS_CAUSE_REQUESTED_CHAN_UNAVAIL		44
	- TRIS_CAUSE_PRE_EMPTED				45
	- TRIS_CAUSE_FACILITY_NOT_SUBSCRIBED  		50
	- TRIS_CAUSE_OUTGOING_CALL_BARRED     		52
	- TRIS_CAUSE_INCOMING_CALL_BARRED     		54
	- TRIS_CAUSE_BEARERCAPABILITY_NOTAUTH		57
	- TRIS_CAUSE_BEARERCAPABILITY_NOTAVAIL     	58
	- TRIS_CAUSE_BEARERCAPABILITY_NOTIMPL		65
	- TRIS_CAUSE_CHAN_NOT_IMPLEMENTED     		66
	- TRIS_CAUSE_FACILITY_NOT_IMPLEMENTED      	69
	- TRIS_CAUSE_INVALID_CALL_REFERENCE		81
	- TRIS_CAUSE_INCOMPATIBLE_DESTINATION		88
	- TRIS_CAUSE_INVALID_MSG_UNSPECIFIED  		95
	- TRIS_CAUSE_MANDATORY_IE_MISSING			96
	- TRIS_CAUSE_MESSAGE_TYPE_NONEXIST			97
	- TRIS_CAUSE_WRONG_MESSAGE				98
	- TRIS_CAUSE_IE_NONEXIST				99
	- TRIS_CAUSE_INVALID_IE_CONTENTS			100
	- TRIS_CAUSE_WRONG_CALL_STATE			101
	- TRIS_CAUSE_RECOVERY_ON_TIMER_EXPIRE		102
	- TRIS_CAUSE_MANDATORY_IE_LENGTH_ERROR		103
	- TRIS_CAUSE_PROTOCOL_ERROR			111
	- TRIS_CAUSE_INTERWORKING				127

The range 128-255 is private cause codes. Our private causes are:

	- TRIS_CAUSE_ANSWERED_ELSEWHERE			200

For more information:
- \ref app_dial.c
*/

/*! \name Causes for disconnection (from Q.931) 
	These are the internal cause codes used in Trismedia.
	\ref AstCauses
*/
/*@{ */
#define TRIS_CAUSE_UNALLOCATED				1
#define TRIS_CAUSE_NO_ROUTE_TRANSIT_NET			2
#define TRIS_CAUSE_NO_ROUTE_DESTINATION			3
#define TRIS_CAUSE_CHANNEL_UNACCEPTABLE			6
#define TRIS_CAUSE_CALL_AWARDED_DELIVERED		7
#define TRIS_CAUSE_NORMAL_CLEARING			16
#define TRIS_CAUSE_USER_BUSY				17
#define TRIS_CAUSE_NO_USER_RESPONSE			18
#define TRIS_CAUSE_NO_ANSWER				19
#define TRIS_CAUSE_SUBSCRIBER_ABSENT			20
#define TRIS_CAUSE_CALL_REJECTED				21
#define TRIS_CAUSE_NUMBER_CHANGED			22
#define TRIS_CAUSE_DESTINATION_OUT_OF_ORDER		27
#define TRIS_CAUSE_INVALID_NUMBER_FORMAT			28
#define TRIS_CAUSE_FACILITY_REJECTED			29
#define TRIS_CAUSE_RESPONSE_TO_STATUS_ENQUIRY		30
#define TRIS_CAUSE_NORMAL_UNSPECIFIED			31
#define TRIS_CAUSE_NORMAL_CIRCUIT_CONGESTION		34
#define TRIS_CAUSE_NETWORK_OUT_OF_ORDER			38
#define TRIS_CAUSE_NORMAL_TEMPORARY_FAILURE		41
#define TRIS_CAUSE_SWITCH_CONGESTION			42
#define TRIS_CAUSE_ACCESS_INFO_DISCARDED			43
#define TRIS_CAUSE_REQUESTED_CHAN_UNAVAIL		44
#define TRIS_CAUSE_PRE_EMPTED				45
#define TRIS_CAUSE_FACILITY_NOT_SUBSCRIBED  		50
#define TRIS_CAUSE_OUTGOING_CALL_BARRED     		52
#define TRIS_CAUSE_INCOMING_CALL_BARRED     		54
#define TRIS_CAUSE_BEARERCAPABILITY_NOTAUTH		57
#define TRIS_CAUSE_BEARERCAPABILITY_NOTAVAIL     	58
#define TRIS_CAUSE_BEARERCAPABILITY_NOTIMPL		65
#define TRIS_CAUSE_CHAN_NOT_IMPLEMENTED     		66
#define TRIS_CAUSE_FACILITY_NOT_IMPLEMENTED      	69
#define TRIS_CAUSE_INVALID_CALL_REFERENCE		81
#define TRIS_CAUSE_INCOMPATIBLE_DESTINATION		88
#define TRIS_CAUSE_INVALID_MSG_UNSPECIFIED  		95
#define TRIS_CAUSE_MANDATORY_IE_MISSING			96
#define TRIS_CAUSE_MESSAGE_TYPE_NONEXIST			97
#define TRIS_CAUSE_WRONG_MESSAGE				98
#define TRIS_CAUSE_IE_NONEXIST				99
#define TRIS_CAUSE_INVALID_IE_CONTENTS			100
#define TRIS_CAUSE_WRONG_CALL_STATE			101
#define TRIS_CAUSE_RECOVERY_ON_TIMER_EXPIRE		102
#define TRIS_CAUSE_MANDATORY_IE_LENGTH_ERROR		103
#define TRIS_CAUSE_PROTOCOL_ERROR			111
#define TRIS_CAUSE_INTERWORKING				127

/* Private Cause codes for Trismedia */
#define TRIS_CAUSE_ANSWERED_ELSEWHERE			200

/* Special Trismedia aliases */
#define TRIS_CAUSE_BUSY 					TRIS_CAUSE_USER_BUSY
#define TRIS_CAUSE_FAILURE 				TRIS_CAUSE_NETWORK_OUT_OF_ORDER
#define TRIS_CAUSE_NORMAL 				TRIS_CAUSE_NORMAL_CLEARING
#define TRIS_CAUSE_NOANSWER	 			TRIS_CAUSE_NO_ANSWER
#define TRIS_CAUSE_CONGESTION	 			TRIS_CAUSE_NORMAL_CIRCUIT_CONGESTION
#define TRIS_CAUSE_UNREGISTERED				TRIS_CAUSE_SUBSCRIBER_ABSENT
#define TRIS_CAUSE_NOTDEFINED 				0
#define TRIS_CAUSE_NOSUCHDRIVER				TRIS_CAUSE_CHAN_NOT_IMPLEMENTED
/*@{ */

#endif /* _TRISMEDIA_CAUSES_H */
