#!/bin/sh
CLIARGS="$*"		# Grab any args passed to safe_trismedia
TTY=			# TTY (if you want one) for Trismedia to run on
CONSOLE=no		# Whether or not you want a console
#NOTIFY=ben@alkaloid.net	# Who to notify about crashes
MACHINE=`hostname`      # To specify which machine has crashed when getting the mail
DUMPDROP=/tmp
DIR=`dirname $0`
BINDIR=`cd $DIR && pwd`
#
# Don't fork when running "safely"
#
TRISARGS=""
if [ "$TTY" != "" ]; then
	if [ -c /dev/tty${TTY} ]; then
		TTY=tty${TTY}
	elif [ -c /dev/vc/${TTY} ]; then
		TTY=vc/${TTY}
	else
		echo "Cannot find your TTY (${TTY})" >&2
		exit 1
	fi
	TRISARGS="${TRISARGS}"
	if [ "$CONSOLE" != "no" ]; then
		TRISARGS="${TRISARGS} -c"
	fi
fi
if [ ! -w ${DUMPDROP} ]; then	
	echo "Cannot write to ${DUMPDROP}" >&2
	exit 1
fi

#
# Let Trismedia dump core
#
ulimit -c unlimited

#
# Run scripts to set any environment variables or do any other system-specific setup needed
#

if [ -d /etc/trismedia/startup.d ]; then
	for script in /etc/trismedia/startup.d/*.sh; do
		if [ -x ${script} ]; then
			source ${script}
		fi
	done
fi

run_mtp3d()
{
	while :; do 

		if [ "$TTY" != "" ]; then
			cd /tmp
			stty sane < /dev/${TTY}
			${BINDIR}/mtp3d ${CLIARGS} ${TRISARGS} >& /dev/${TTY} < /dev/${TTY}
		else
			cd /tmp
			${BINDIR}/mtp3d ${CLIARGS} ${TRISARGS}
		fi
		EXITSTATUS=$?
		echo "mtp3d ended with exit status $EXITSTATUS"
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "mtp3d shutdown normally."
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			let EXITSIGNAL=EXITSTATUS-128
			echo "mtp3d exited on signal $EXITSIGNAL."
			if [ "$NOTIFY" != "" ]; then
				echo "mtp3d on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "mtp3d Died" $NOTIFY
			fi
                        if [ -f /tmp/core ]; then
				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			fi
		else
			if [ "${EXITSTATUS}" = "0" ]; then
				echo "mtp3d ended normally.  Aborting."
				exit 0
			else
				echo "mtp3d died with code $EXITSTATUS."
	                        if [ -f /tmp/core ]; then
					mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
				fi
			fi
		fi
		echo "Automatically restarting mtp3d."
		sleep 4
	done
}

run_mtp3d &
